### ISSUE TITLE
Allow inverse times

### ISSUE THREAD

**Issue by cwrau** [aneeshd/schedule_state#175]
**Is your feature request related to a problem? Please describe.**
I have a "sleep" button to indicate that I've been gone to sleep. I use the press time of this button to have a specific temperature in the schedule state. 

`button press` - `button press + 8 hours`

Obviously this can, and most often does, cross day borders, resulting in a start time of e.g. `23:00` and an end time of `07:00`.

Schedule state then fails to render this state. 

I now have two fairly complex templated states with the same temperature so that I have one for `23:00` - `23:59` and one for `00:00` - `07:00`.

**Describe the solution you'd like**
I'd love for this integration to figure this out by itself, like, if the end time is before the start time, the user obviously means the next day.

**Describe alternatives you've considered**
See my complex setup above.

**Comment by aneeshd** [comment]
@cwrau have you tried using overrides? This should solve your exact need, where the start time is not known in advance but you want the schedule to react to something happening. In your case, you can fire off an override when the button is pressed with duration=8h and start/end not provided. This will automatically create two states; one from now to midnight, the other from midnight to (now+8h).

See the service called "schedule_state.state_override" - you can experiment with it using the Services tab of HA's Developer tools page.

**Comment by aneeshd** [comment]
Although I see now that the max length of an override is restricted to 360 minutes, for no obvious reason. I will fix that.

**Comment by cwrau** [comment]
> @cwrau have you tried using overrides? This should solve your exact need, where the start time is not known in advance but you want the schedule to react to something happening. In your case, you can fire off an override when the button is pressed with duration=8h and start/end not provided. This will automatically create two states; one from now to midnight, the other from midnight to (now+8h).
> 
> See the service called "schedule_state.state_override" - you can experiment with it using the Services tab of HA's Developer tools page.

Yeah, I've been using overrides for short-term settings, and I guess it would be possible to use it for this case, calculating the end time and setting the correct override, but this would require me to completely duplicate the whole temperature schedule logic, because the sleep button is not top priority and should be overridden by the normal schedule, e.g. when I wake up it should stop

**Comment by aneeshd** [comment]
You don't need to calculate the end time, you can just give it the duration. 

As for priority, you can cancel the override by name triggered by whatever logic you use when you wake up. That avoids the need to redo any of the logic. 

Allowing end < start in general can result in unexpected behavior for trivial configuration errors, so it's not very user friendly.

**Comment by cwrau** [comment]
> You don't need to calculate the end time, you can just give it the duration.

Yeah, but calculating the duration is the exact same problem as calculating the end time 😅

And, does the override even survive restarts?

And even more, this schedule is so close to doing exactly what I want, I kinda want to avoid making it more complex on my end 😅

> As for priority, you can cancel the override by name triggered by whatever logic you use when you wake up. That avoids the need to redo any of the logic.

I don't have any wakeup logic 😅

And the point of automation is so I don't have to do anything. And having to press a button in the morning kinda defeats that 😅

> Allowing end < start in general can result in unexpected behavior for trivial configuration errors, so it's not very user friendly.

Mh, I mean, I *kinda* get this, but, what does someone expect when the start time is before the end time, except that it works across day borders?

And, one could document this so the user knows about this

**Comment by aneeshd** [comment]
You said your duration was 8h, now you are saying it is something else.
Yes, overrides survive restarts.
Feel free to submit a pull request for documentation update or improved code.

**Comment by cwrau** [comment]
> You said your duration was 8h, now you are saying it is something else.

Sorry, what I meant was, the duration is 8 hours, but it gets cut short by the other time slices. 
Which is easy in schedule state, as I just have to define these slices, but difficult with home assistant.

**Comment by aneeshd** [comment]
OK, the fact that it is not always 8 hours was a missing detail. I better understand now what you are trying to do.

**Comment by aneeshd** [comment]
Perhaps the event could have an additional attribute to "allow wrapping", that the user has to explicitly specify in an event.

Start>end can happen very easily, which is why wrapping is disabled. You can have an event that is some start time before/after sunset (which varies wildly where I live over the course of the year), and an end time that is based on wall clock (I need to go to bed/wake up at a certain time regardless of what the sun is doing).

**Comment by cwrau** [comment]
> Perhaps the event could have an additional attribute to "allow wrapping", that the user has to explicitly specify in an event.

That would be amazing 😁

> Start>end can happen very easily, which is why wrapping is disabled. You can have an event that is some start time before/after sunset (which varies wildly where I live over the course of the year), and an end time that is based on wall clock (I need to go to bed/wake up at a certain time regardless of what the sun is doing).

I understand, although in that situation I would've intuitively added a condition that checks that the times are in correct order.

---

In general, that all the times are exclusively during the current day and don't wrap, especially the times for the last event of the day, which "ends" at 23:59 and the next event is "coincidentally" the same,, is kinda inconvenient and unintuitive, because if you want to do something predictively, like preheating to reach the target temperature in time, the real end time of the current event, which might be 00:30, or, more importantly, the start time of the next event,, is hidden.

I also have some events that span across day borders conditionally and for them I have conditions like "if today is a free day and it's before 01:00 or if tomorrow is a free day and it's after 01:00" so it gets correctly added. With absolute times this would be easier; I could just say "if today is a free day start from today 00:00 and end at today 01:00" and "if tomorrow is a free day start at tomorrow 00:00 and end at tomorrow 01:00" and I wouldn't have to worry about this event going over into tomorrow.

**Comment by cwrau** [comment]
Thanks for implementing the wrapping times parameter! 

But your pull request only addressed this issue in general, but not the last block I've written above.

What do you think about adding the option to specify absolute datetimes as start / end parameters? Ideally implicitly depending on what the user specifies or with an option like you did for the wrapping feature.

This would cover the last bits I'm struggling with and would eliminate the need for "complex" time-based conditions, which I currently need to specify.

Although I guess this would mean converting all types which are currently strings / times to full datetimes and how the sensor "displays" / "returns" them in its state.

**Comment by aneeshd** [comment]
Using full datetimes is a good idea but will require bigger changes to how everything works internally. If I can think of a nice way to do it, I’ll do it as part of a separate ticket. - aneeshSent from my iPhonePlease excuse any typos or logical fallacies. On Jan 2, 2024, at 15:24, Chris Werner Rau ***@***.***> wrote:﻿
Thanks for implementing the wrapping times parameter!
But your pull request only addressed this issue in general, but not the last block I've written above.
What do you think about adding the option to specify absolute datetimes as start / end parameters? Ideally implicitly depending on what the user specifies or with an option like you did for the wrapping feature.
This would cover the last bits I'm struggling with and would eliminate the need for "complex" time-based conditions, which I currently need to specify.
Although I guess this would mean converting all types which are currently strings / times to full datetimes and how the sensor "displays" / "returns" them in its state.
