### ISSUE TITLE
Trigger recalculate every time a date/time helper changes value.

### ISSUE THREAD

**Issue by valantur** [aneeshd/schedule_state#2]
First of all, I'm very excited about this component! It solves many workaround implementations I have in HA and Node-RED.
It'd be nice to have the scheduler recalculate every time a "time helper" changes its state.

For example, if I set this component to take the value of a time helper called "day_start" as the start time of "day", It would be nice for this component to recalculate when I change the state of the helper. Does that makes sense?
A workaround is to create an automation that listens to a change on each helper and trigger a recalculate, but that kinds of defeats using this component in my case cause I already have something like that in place, just more cumbersome.

Thanks!

**Comment by aneeshd** [comment]
Hi, yes I think I understand what you are asking for. To clarify, do you use your helper as a template value in the start/end definitions?

**Comment by valantur** [comment]
that's correct! I use helpers to provide an UI for my scheduler times. That way anyone is my house can change the times without knowing YAML.

**Comment by aneeshd** [comment]
@valantur great suggestion - see if the new version works for what you are trying to do

**Comment by valantur** [comment]
hmm for some reason there are a couple of things not working for me:
1- This logic here always applies the "night" schedule, not sure why:

- platform: schedule_state
  name: daily schedule
  default_state: away
  events:
    - start_template: states('input_datetime.thermostat_program_morning_start')
      end_template: states('input_datetime.thermostat_program_day_start')
      state: morning
      condition:
        - condition: state
          entity_id: input_boolean.thermostat_away
          state: "off"
    - start_template: states('input_datetime.thermostat_program_day_start')
      end_template: states('input_datetime.thermostat_program_evening_start')
      state: day
      condition:
        - condition: state
          entity_id: input_boolean.thermostat_away
          state: "off"
    - start_template: states('input_datetime.thermostat_program_evening_start')
      end_template: states('input_datetime.thermostat_program_night_start')
      state: evening
      condition:
        - condition: state
          entity_id: input_boolean.thermostat_away
          state:  "off"
    - start_template: states('input_datetime.thermostat_program_night_start')
      end_template: states('input_datetime.thermostat_program_morning_start')
      state: night
      condition:
        - condition: state
          entity_id: input_boolean.thermostat_away
          state: "off"

The Condition part seems to be working fine because as soon as I turn ON the thermostat_away input boolean the schedule switches to away (the default option). However, not matter what time of the day it is, this chain of events always evaluate to "night". Am I entering something wrong here?

Thanks!

**Comment by valantur** [comment]
Now that I think about it, the only thing special about night is that it starts on day 1 and ends on day 2... does this component handle different days in its logic?

**Comment by valantur** [comment]
A quick update:

I re-read the docs and make some changes hoping it would work, but still doesn't. I no longer have a single "night" event that spans two days, but two. The first one goes from 00:00 to the morning start (I skipped the "start" directive, the last one goes from "night_start" until midnight, skipping the "end" directive:  

events:
    - end_template: states('input_datetime.thermostat_program_morning_start')
      state: night
      condition:
        - condition: state
          entity_id: input_boolean.thermostat_away
          state: "off"
    - start_template: states('input_datetime.thermostat_program_morning_start')
      end_template: states('input_datetime.thermostat_program_day_start')
      state: morning
      condition:
        - condition: state
          entity_id: input_boolean.thermostat_away
          state: "off"
    - start_template: states('input_datetime.thermostat_program_day_start')
      end_template: states('input_datetime.thermostat_program_evening_start')
      state: day
      condition:
        - condition: state
          entity_id: input_boolean.thermostat_away
          state: "off"
    - start_template: states('input_datetime.thermostat_program_evening_start')
      end_template: states('input_datetime.thermostat_program_night_start')
      state: evening
      condition:
        - condition: state
          entity_id: input_boolean.thermostat_away
          state:  "off"
    - start_template: states('input_datetime.thermostat_program_night_start')
      state: night
      condition:
        - condition: state
          entity_id: input_boolean.thermostat_away
          state: "off"

**Comment by aneeshd** [comment]
That sounds like it is working as intended. The schedule spans a single 24-hour period (midnight to midnight). I can try to make to make this more clear in the documentation.

The schedule is refreshed every 6 hours by default, so it is always ready with an up-to-date event schedule.

**Comment by aneeshd** [comment]
One thing that could be improved is to more gracefully handle an event that eg starts at 22:00 and ends at 3:00. Feel free to add a new issue for that. The current behaviour is non-obvious.
