### ISSUE TITLE
Add icon_color support

### ISSUE THREAD

**Issue by Pulpyyyy** [aneeshd/schedule_state#209]
Hello

We can already specify `icon` depending the state value
But we can't set `icon_color` (or it's not used by HA cards if `extra_attributes`)
Can this feature be added ?

Regards

**Comment by aneeshd** [comment]
As far as I know, icon_color is not an attribute recognized by Lovelace (HA front end)

**Comment by aneeshd** [comment]
See https://developers.home-assistant.io/docs/core/entity/#advanced-properties

**Comment by aneeshd** [comment]
does not appear to be supported by HA
