### ISSUE TITLE
Strange behaviour of the component, not sure if it is an error

### ISSUE THREAD

**Issue by tj551955** [aneeshd/schedule_state#257]
The times configured to the entity in the .yaml file are not shown correctly in the developer tools of HA.

## Version of the schedule_state component
0.19.4

## Version of HA
Core 2024.5.4
Supervisor 2024.05.1
Operating System 12.3
Frontend 20240501.1

## Configuration

- platform: schedule_state
  name: p1_mo
  default_state: "aus"
  events:
    - start: "10:40"
      end: "10:41"
      state: "an"
      icon: mdi:fountain

no logs, even when I enable debug logging for the component

## Describe the bug
I set the configuration like above and reload the configuration. Than I check the state of the entity in the developer tools.
Before the start time has arrived it looks like this: ![grafik](https://github.com/aneeshd/schedule_state/assets/74710010/dc7c4a3a-a57f-41b2-a625-040face0fd02)
When the time changes to 10:40 it looks like this:
![grafik](https://github.com/aneeshd/schedule_state/assets/74710010/1d51d7fc-97f3-4a0f-b93e-ce2fd0c3133c)
When the time changes to 10:41 it looks like this: 
![grafik](https://github.com/aneeshd/schedule_state/assets/74710010/2a028e26-c5bc-49a1-b88a-fdb8a2a808e3)

So the state is correct but the times are messed up.
I would have expected that the start time is always 10:40 and the end time is always 10:41 even right after the reload of the configuration. I'd like to have it as expected because I need the correct times for other purposes within HA.

## Debug log
no logs, even when I enable debug logging for the component

**Comment by aneeshd** [comment]
It seems to be behaving exactly as intended. start/end attributes reflect the start and end times of the **current** state.

In example 1, it is showing the default (currently active) state "aus" until 10:40

In example 2, it is showing the currently active state "an" from 10:40 to 10:41

In example 3, it is again showing the default state "aus" from 10:41 to 10:40 of the next day. This one might be a bit confusing, it is looking forward to the next state transition on the next day if the state at midnight (0:00) matches the state at 0:01. See README for caveats.

**Comment by tj551955** [comment]
Ok. Thanks for the explanation. Then I understand the philosophy behind.
I need to have the configured times for other purposes. Is it possible to add the configured times also as attributes? Should I than open a feature request?

**Comment by aneeshd** [comment]
Yes, please submit a feature request. - aneeshSent from my iPhonePlease excuse any typos or logical fallacies. On May 27, 2024, at 01:48, tj551955 ***@***.***> wrote:﻿
Ok. Thanks for the explanation. Then I understand the philosophy behind.
I need to have the configured times for other purposes. Is it possible to add the configured times also as attributes? Should I than open a feature request?
