### ISSUE TITLE
Return previous state when unable to evaluate template due to home assistant not being fully loaded

### ISSUE THREAD

**Issue by valantur** [aneeshd/schedule_state#31]
**Is your feature request related to a problem? Please describe.**
I use start_template and end_template a bunch with this integration. These templates read the values of several datetime helpers.
It looks like this integration is loaded before those helpers, and therefore the schedule takes on the value set as default (as you wrote in the docs). In my case, this totally breaks the logic of my automation for 5 minutes, until the schedule gets evaluated.

**Describe the solution you'd like**
Ideally, I'd like this integration to wait until home-assistant is fully loaded before running. Or at least wait until the input_datetime domain is fully loaded... I don't know what provisions exist within home assistant to facilitate this.
An alternative to this would be to remember the previous state (before Home Assistant was restarted) and don't return the default value ONLY the first time it fails to evaluate. That way, if the issue is caused by the templates themselves being wrong, then it would be noticeable after 5 minutes because the integration will suddenly return the default value, but if it was a problem of some helpers nor being loaded, the status will remain the same it was before the restart until those 5 minutes have passed, then re-evaluate correctly.

**Describe alternatives you've considered**
I also think it's a good idea to allow users to set the variable "MINUTES_TO_REFRESH_ON_ERROR" so that this issue is minimized if it can't be solved.

I really like this integration, thanks for your work!

**Comment by aneeshd** [comment]
I think I finally figured out how to delay loading until other stuff has started! Please try 0.14.0. Also added a configurable "minutes_to_refresh_on_error" at the top level should you need it.
