### ISSUE TITLE
Update override with `set_override`, without first `clear_overrides`

### ISSUE THREAD

**Issue by nagyrobi** [aneeshd/schedule_state#47]
## Version of the schedule_state component

0.15.3
## Configuration
Not relevant - any valid will do
## Describe the bug
Steps to reproduce:

First issue - `states` attribute increasing:
- set overrides repeatedly with the `set_override` service, each time specifying a new `state`
- result: `states` attribute will be populated with all the `state` values set with the service calls above
- expected result: in `states` attribute, the state corresponding to the override should be updated/replaced with each service call

Second issue - `end`, `friendly_end` attributes (and presumably the corresponding time) only increasing:
- set overrides repeatedly with the `set_override` service, each time specifying a new `duration`. First increase it a couple of time, then decrease it.
- result: `end`, `friendly_end` attributes show that the time will only be updated if the `duration` increases. 
- expected result: on each service call, the time should be recalculated according to the `duration`, regardless if it's smaller or bigger than what it was

Note that calling `set_override` with `end` parameter works as expected, can both increase and decrease the time.

There is `clear_overrides` service, which of course can be first called within the automation/script to reset the schedule, however that has a negative side effect that the main state of the entity will momentarily switch to one of a configured event for a short moment, which may furtherly trigger unexpected things in HA.

Calling `set_override` without `clear_overrides` before it would allow us to update the override parameters without any intermediate, unexpected state changes.

## Debug log
N/A

**Comment by aneeshd** [comment]
How about `set_override` allows you to pass in an arbitrary ID, then subsequent `set_override` with the same ID would modify the previous override? We could also have a `remove_override` (with ID) to remove a specific one, instead of clearing all overrides.

**Comment by nagyrobi** [comment]
A bit cumbersome I guess. I think from user's perspective, how to manage the IDs from the UI in a way to pass the WAF test...?

*WAF test = Wife Acceptance Factor test :)

**Comment by nagyrobi** [comment]
I think it could be handled as an attribute holding a list of IDs of active overrides. 
- If an ID was not specified, a string based on the timestamp of the moment it was set could be generated automatically.
- If only one override is present in the list, removing/modifying services can ommit the requirement of specifying the ID, they act in the single override they find, whatever ID it has.
- If multiple overrides are present, services should gracefully fail with a notification message in the dashboard/logs, that override ID needs to be specified

**Comment by aneeshd** [comment]
That all sounds needlessly complex. I wonder if you are using overrides in a way I had not anticipated?

I have 2 kinds of overrides in my setup, both controlled from the UI. They work in a similar way.

- I have a schedule for the thermostat setting during the day, with logic for weekends, holidays, doors/windows open, outside temp, etc. But I have a state for "toasty" (ie set the heat on high no matter what). A button on the UI sets the state to toasty for 30 minutes (start=now() duration=30), another button cancels the override (clears all overrides). 
- I have various schedules for lights in different parts of the house, to turn things off at night. But I can set an override by pushing a button in the UI to keep the lights on for another 30 minutes.

Currently, if you push the set button repeatedly, yes you currently get multiple overrides, but things work as expected and the extra overrides don't bother anybody.

With the change, each set override will have a static id defined in the service call. If you push the set button, the override will either be created, or it will be adjusted. There will be a single override instead of multiple. The cancel button will use the same id.

Can you describe your use case?

**Comment by nagyrobi** [comment]
My use case is very similar, actually I only need 2 kinds of overrides, for a central heating system.
Currently I use 7 schedules for heating, but they will be a few more in the future. Each schedule works for a separate heating zone.

- The house has a general home/away sensor, it's derived from presence detection. An override is needed for that, in order to set temperatures corresponding to the away state. (I don't use climate's own home/away mode because it's less flexible, eg. for one type of cimate the away temperature is hardcoded in the yaml, can't be specified as template, the other type of climate doesn't even support away mode in its integration at all). So what I need is simply an override working in real time, start and end are not known, instead, it's tied to the state of an aggregated presence sensor, or binary sensor etc. It's the same sensor triggering the override for all the schedules, and currently it's the same temperature value being set for all the zones. In the UI I only show the state of the presence sensor, no interaction with that.
- There's the case also known as "party mode" where we need an override to set a different temperature "no matter what" for a desired period of time. I present a datetime picker and boolean switch in the UI, when I turn that on the datetime self-populates with current time +1 hour thus by default the duration becomes 1 hour. But the user can any time change the duration to more, or to less, depending on the actual needs. This can even be the whole week-end, or even longer, depends on what the requirement is. Can literally be a party leaning into the night and next day, bit can also be visiting guests staying for a few days, but we also had sadly the case when a family member was ill, and constantly needed a warmer room for about a week. This also covers your "toasty" case.

I figured out how to handle both by simply relying on your exceptional top-to-bottom layered processing rule, this is very strong because placing events matching all day at the bottom, tied to the presence sensor, and to an override input_boolean respectively (https://github.com/aneeshd/schedule_state/issues/49#issuecomment-1259034299), I can achieve what I want.

I first tried to achieve these goals using the override services you offer, and found this bug during trying, however, I discovered that it becomes a lot more complicated on the automations side to implement them. Instead, I'll just stay with regular events at the bottom as I described above.

**Comment by nagyrobi** [comment]
On long term I consider adding mmwave sensors for human presence detection in the rooms, and make real time overrides based on that. Thinking about either an override in the schedule, or just applying a bias to the target temps (eg. no person detected for a timeout, decrease target temp by 1 degree, but keep schedule running).

**Comment by aneeshd** [comment]
I think this change will make overrides a bit easier to deal with. Of course you still have the option to work with conditional layers.
