### ISSUE TITLE
schedule_state does not install

### ISSUE THREAD

**Issue by Reynders1** [aneeshd/schedule_state#79]
## Version of the schedule_state component
f755347 - latest available on HACS today

## Configuration

```logger:
  default: warning # only log errors
  logs:
    custom_components.schedule_state: debug
```

Home Assistant 2023.1.4
Supervisor 2022.12.1
Operating System 9.4
Frontend 20230110.0 - latest

## Describe the bug
I installed schedule_state like any other integrations, but it does not load. No service is available, no error in the log, no sensor created.

What do I missed?

I have another instance of Homeassistant where schedule_state works perfectly!

## Debug log

```text

2023-01-16 13:15:21.795 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration schedule_state which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

```

**Comment by aneeshd** [comment]
Most likely you have not defined a schedule_state component in your configuration.yaml. You won't see any services or sensors until you do that.
