### ISSUE TITLE
Feature: Have the next state as an attribute.

### ISSUE THREAD

**Issue by vlebourl** [aneeshd/schedule_state#80]
**Is your feature request related to a problem? Please describe.**
Nope

**Describe the solution you'd like**
Would it be possible to have next state as an attribute?

**Describe alternatives you've considered**

**Additional context**

Hey, I just installed your integration, and it's a game changer! It's perfect for setting a thermostat with different presets at different times in different rooms. I was looking for something like this for a while and I'm so happy I found it. I started looking at the code, but it's more complicated than I anticipated. I was wondering how hard it would be to add the next computed state as an attribute? As you wrote the code, you probably have an idea if it's doable or not. 

Cheers for the awesome work!

**Comment by aneeshd** [comment]
Thanks! I think this should be possible to add. Let me think about it for a few days.

**Comment by aneeshd** [comment]
@vlebourl let me know if this works in your setup, I've tried it for a few days now and it seems to work

**Comment by vlebourl** [comment]
Perfect! thanks :)
